my-snowflake-db-sso:
  outputs:
    dev:
      account: <<accountname>>
      authenticator: externalbrowser
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: <<databasename>>
      query_tag: sso_connection
      retry_all: false
      retry_on_database_errors: false
      reuse_connections: false
      role: <<role>>
      schema: <<schema>>
      threads: 1
      type: snowflake
      user: <<username>>
      warehouse: <<warehousename>>
  target: dev

my_snowflake_db:
  outputs:
    dev:
      type: snowflake
      account: <<account_id>>
      user: <<user_name>>
      password: <<user_password>>
      role: <<role>>
      warehouse: <<WH>>
      database: <<DB>>
      schema: <<schema>>
      threads: 2
  target: dev
