my-snowflake-db-sso:
  outputs:
    dev:
      account: <<accountname>>
      authenticator: externalbrowser
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: <<databasename>>
      query_tag: sso_connection
      retry_all: false
      retry_on_database_errors: false
      reuse_connections: false
      role: <<role>>
      schema: <<schema>>
      threads: 1
      type: snowflake
      user: <<username>>
      warehouse: <<warehousename>>
  target: dev

sample_sales:
  outputs:
    dev:
      account: <<accountname>>
      database: <<databasename>>
      password: <<password>>
      role: <<role>>
      schema: <<schema>>
      threads: 2
      type: <<connectiontype>>
      user: <<username>>
      warehouse: <<warehousename>>
  target: dev
