version: 2

sources:
  - name: SOURCE
    schema: TGT_WRKS
    tables:
      - name: customer_account
        identifier: src_customers_account
      - name: email_response
        identifier: src_email_response